# Generated by Django 2.0.2 on 2018-03-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
