# Generated by Django 2.0.2 on 2018-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='polygons_changed',
        ),
        migrations.AddField(
            model_name='commit',
            name='new_version',
            field=models.FileField(default='File1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='old_version',
            field=models.FileField(default='File2', upload_to=''),
            preserve_default=False,
        ),
    ]
