# Generated by Django 2.0.2 on 2018-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180306_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
