# Generated by Django 2.0.3 on 2018-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180306_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='title',
            field=models.CharField(default='A 3D Model', max_length=64),
            preserve_default=False,
        ),
    ]
