# Generated by Django 2.0.3 on 2018-03-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_model3d_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='title',
            field=models.CharField(default='Added textures', max_length=64),
            preserve_default=False,
        ),
    ]
