# Generated by Django 2.0.3 on 2018-03-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_commit_old_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='filename',
        ),
    ]
