# Generated by Django 2.0.3 on 2018-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_model3d_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='polygons',
        ),
        migrations.AddField(
            model_name='model3d',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
