# Generated by Django 2.0.3 on 2018-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180309_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='new_textures',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
