# Generated by Django 2.0.3 on 2018-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_commit_new_textures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='new_textures',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
