# Generated by Django 2.0.3 on 2018-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180313_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='new_textures',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
