# Generated by Django 2.0.3 on 2018-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180313_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
