# Generated by Django 2.0.3 on 2018-03-30 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_commit_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='belongs_to_model',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.Model3D'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='commited_by',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='details',
            field=models.TextField(default='....'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model3d',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='core.Model3D'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='........'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
