# Generated by Django 2.0.4 on 2018-05-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='commited_by',
            new_name='committed_by',
        ),
        migrations.AlterField(
            model_name='revision',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.Model3D'),
        ),
    ]
