# Generated by Django 2.0.4 on 2018-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180501_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
