# Generated by Django 2.0.4 on 2018-05-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180502_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='belongs_to_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.Model3D'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.Model3D'),
        ),
    ]
