# Generated by Django 2.0.4 on 2018-05-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180502_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='belongs_to_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.Model3D'),
        ),
    ]
