# Generated by Django 2.0.4 on 2018-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180502_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='commit_mesh',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
