# Generated by Django 2.0.4 on 2018-05-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_revision_commit_mesh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='commit_title',
        ),
    ]
