# Generated by Django 2.0.4 on 2018-05-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_revision_commit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='status',
            field=models.CharField(default='PENDING APPROVAL', max_length=20),
        ),
    ]
