# Generated by Django 2.0.4 on 2018-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180503_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='viewcount',
            field=models.BigIntegerField(default=0),
        ),
    ]
