# Generated by Django 2.0.4 on 2018-05-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_post_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='fork_of',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forks', to='core.Model3D'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='forkcount',
            field=models.BigIntegerField(default=0),
        ),
    ]
