# Generated by Django 2.0.4 on 2018-05-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180505_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forks', to='core.Model3D'),
        ),
    ]
