# Generated by Django 2.0.4 on 2018-05-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180505_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='is_fork',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model3d',
            name='fork_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Model3D'),
        ),
    ]
