# Generated by Django 2.0.4 on 2018-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180505_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='software',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
