# Generated by Django 2.0.5 on 2018-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_profile_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
    ]
