# Generated by Django 2.0.5 on 2018-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180506_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='nth_commit',
            field=models.BigIntegerField(default=0),
        ),
    ]
