# Generated by Django 2.0.2 on 2018-02-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('profile_picture', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('favorites', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('models_3d', models.TextField()),
                ('followed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_auth.User')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to='main_auth.User')),
            ],
        ),
    ]
