# Generated by Django 2.0.2 on 2018-02-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0005_comment_commit_model3d_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='main_auth.Model3D'),
        ),
        migrations.AlterField(
            model_name='user',
            name='models_3d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_3d', to='main_auth.Model3D'),
        ),
    ]
