# Generated by Django 2.0.2 on 2018-02-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0007_auto_20180219_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='models_3d',
        ),
    ]
