# Generated by Django 2.0.2 on 2018-02-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0008_remove_user_models_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='models_3d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models_3d', to='main_auth.Model3D'),
        ),
    ]
