# Generated by Django 2.0.2 on 2018-02-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0009_auto_20180219_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='present_model',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='previous_model',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='models_3d',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_auth.Post'),
        ),
        migrations.AddField(
            model_name='commit',
            name='belongs_to_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_auth.Model3D'),
        ),
        migrations.AddField(
            model_name='commit',
            name='commited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_auth.User'),
        ),
        migrations.AddField(
            model_name='commit',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_by', to='main_auth.User'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to='main_auth.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_auth.User'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='filename',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_auth.User'),
        ),
    ]
