# Generated by Django 2.0.2 on 2018-02-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0010_auto_20180219_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='commits',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='main_auth.Post'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='belongs_to_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='main_auth.Model3D'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_auth.User'),
        ),
    ]
