# Generated by Django 2.0.2 on 2018-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0012_auto_20180220_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='filename',
            field=models.FilePathField(),
        ),
    ]
