# Generated by Django 2.0.2 on 2018-02-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_auth', '0014_auto_20180220_1004'),
    ]

    operations = [
    ]
